# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'Light' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tableviewSwift
  pod 'CocoaMQTT'

end
